package jsco:hello-p2-world;

world hello-p2-world {
    import wasi:cli/environment@0.2.11;
    import wasi:cli/exit@0.2.11;
    import wasi:io/error@0.2.11;
    import wasi:io/streams@0.2.11;
    import wasi:cli/stdin@0.2.11;
    import wasi:cli/stdout@0.2.11;
    import wasi:cli/stderr@0.2.11;

    export wasi:cli/run@0.2.11;
}
