package jsco:implementer-p2@0.1.0;

world implementer-p2 {
    // Export WASI interfaces with fake implementations
    export wasi:cli/environment@0.2.11;
    export wasi:cli/exit@0.2.11;
    export wasi:cli/stdin@0.2.11;
    export wasi:cli/stdout@0.2.11;
    export wasi:cli/stderr@0.2.11;
    export wasi:random/random@0.2.11;
    export wasi:clocks/monotonic-clock@0.2.11;
    export wasi:clocks/wall-clock@0.2.11;
    export jsco:test/echo-primitives@0.1.0;
    export jsco:test/echo-compound@0.1.0;
    export jsco:test/echo-algebraic@0.1.0;
    export jsco:test/echo-complex@0.1.0;
}
