// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod jsco {
    pub mod test {
        /// Sink: import-side functions that wasm calls to push transformed data back to JS
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod echo_sink {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn report_primitive(label: &str, value: &str) -> () {
                unsafe {
                    let vec0 = label;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = value;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "jsco:test/echo-sink@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "report-primitive"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn report_record(label: &str, x: f64, y: f64) -> () {
                unsafe {
                    let vec0 = label;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "jsco:test/echo-sink@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "report-record"]
                        fn wit_import1(_: *mut u8, _: usize, _: f64, _: f64);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(
                        _: *mut u8,
                        _: usize,
                        _: f64,
                        _: f64,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import1(
                            ptr0.cast_mut(),
                            len0,
                            _rt::as_f64(&x),
                            _rt::as_f64(&y),
                        )
                    };
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod jsco {
        pub mod test {
            /// Primitives: all numeric types, bool, char, string
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod echo_primitives {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_bool_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_bool(_rt::bool_lift(arg0 as u8));
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_u8_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_u8(arg0 as u8);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_u16_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_u16(arg0 as u16);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_u32_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_u32(arg0 as u32);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_u64_cabi<T: Guest>(arg0: i64) -> i64 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_u64(arg0 as u64);
                    _rt::as_i64(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_s8_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_s8(arg0 as i8);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_s16_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_s16(arg0 as i16);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_s32_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_s32(arg0);
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_s64_cabi<T: Guest>(arg0: i64) -> i64 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_s64(arg0);
                    _rt::as_i64(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_f32_cabi<T: Guest>(arg0: f32) -> f32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_f32(arg0);
                    _rt::as_f32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_f64_cabi<T: Guest>(arg0: f64) -> f64 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_f64(arg0);
                    _rt::as_f64(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_char_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_char(_rt::char_lift(arg0 as u32));
                    _rt::as_i32(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_string_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::echo_string(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_echo_string<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                pub trait Guest {
                    fn echo_bool(v: bool) -> bool;
                    fn echo_u8(v: u8) -> u8;
                    fn echo_u16(v: u16) -> u16;
                    fn echo_u32(v: u32) -> u32;
                    fn echo_u64(v: u64) -> u64;
                    fn echo_s8(v: i8) -> i8;
                    fn echo_s16(v: i16) -> i16;
                    fn echo_s32(v: i32) -> i32;
                    fn echo_s64(v: i64) -> i64;
                    fn echo_f32(v: f32) -> f32;
                    fn echo_f64(v: f64) -> f64;
                    fn echo_char(v: char) -> char;
                    fn echo_string(v: _rt::String) -> _rt::String;
                }
                #[doc(hidden)]
                macro_rules! __export_jsco_test_echo_primitives_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-bool")] unsafe extern "C"
                        fn export_echo_bool(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_bool_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-u8")] unsafe extern "C" fn
                        export_echo_u8(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_u8_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-u16")] unsafe extern "C" fn
                        export_echo_u16(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_u16_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-u32")] unsafe extern "C" fn
                        export_echo_u32(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_u32_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-u64")] unsafe extern "C" fn
                        export_echo_u64(arg0 : i64,) -> i64 { unsafe {
                        $($path_to_types)*:: _export_echo_u64_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-s8")] unsafe extern "C" fn
                        export_echo_s8(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_s8_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-s16")] unsafe extern "C" fn
                        export_echo_s16(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_s16_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-s32")] unsafe extern "C" fn
                        export_echo_s32(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_s32_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-s64")] unsafe extern "C" fn
                        export_echo_s64(arg0 : i64,) -> i64 { unsafe {
                        $($path_to_types)*:: _export_echo_s64_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-f32")] unsafe extern "C" fn
                        export_echo_f32(arg0 : f32,) -> f32 { unsafe {
                        $($path_to_types)*:: _export_echo_f32_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-f64")] unsafe extern "C" fn
                        export_echo_f64(arg0 : f64,) -> f64 { unsafe {
                        $($path_to_types)*:: _export_echo_f64_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-char")] unsafe extern "C"
                        fn export_echo_char(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_char_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-primitives@0.1.0#echo-string")] unsafe extern "C"
                        fn export_echo_string(arg0 : * mut u8, arg1 : usize,) -> * mut u8
                        { unsafe { $($path_to_types)*:: _export_echo_string_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "cabi_post_jsco:test/echo-primitives@0.1.0#echo-string")] unsafe
                        extern "C" fn _post_return_echo_string(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_echo_string::<$ty > (arg0) }
                        } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_jsco_test_echo_primitives_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// Compound: records, tuples, lists, options, results
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod echo_compound {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct Point {
                    pub x: f64,
                    pub y: f64,
                }
                impl ::core::fmt::Debug for Point {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Point")
                            .field("x", &self.x)
                            .field("y", &self.y)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct LabeledPoint {
                    pub label: _rt::String,
                    pub coords: Point,
                    pub elevation: Option<f64>,
                }
                impl ::core::fmt::Debug for LabeledPoint {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("LabeledPoint")
                            .field("label", &self.label)
                            .field("coords", &self.coords)
                            .field("elevation", &self.elevation)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_tuple2_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let result1 = T::echo_tuple2((
                        arg0 as u32,
                        _rt::string_lift(bytes0),
                    ));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let (t3_0, t3_1) = result1;
                    *ptr2.add(0).cast::<i32>() = _rt::as_i32(t3_0);
                    let vec4 = (t3_1.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                        .cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_echo_tuple2<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l1 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_tuple3_cabi<T: Guest>(
                    arg0: f32,
                    arg1: f32,
                    arg2: f32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_tuple3((arg0, arg1, arg2));
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let (t2_0, t2_1, t2_2) = result0;
                    *ptr1.add(0).cast::<f32>() = _rt::as_f32(t2_0);
                    *ptr1.add(4).cast::<f32>() = _rt::as_f32(t2_1);
                    *ptr1.add(8).cast::<f32>() = _rt::as_f32(t2_2);
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_record_cabi<T: Guest>(
                    arg0: f64,
                    arg1: f64,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_record(Point { x: arg0, y: arg1 });
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let Point { x: x2, y: y2 } = result0;
                    *ptr1.add(0).cast::<f64>() = _rt::as_f64(x2);
                    *ptr1.add(8).cast::<f64>() = _rt::as_f64(y2);
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_nested_record_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: f64,
                    arg3: f64,
                    arg4: i32,
                    arg5: f64,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::echo_nested_record(LabeledPoint {
                        label: _rt::string_lift(bytes0),
                        coords: Point { x: arg2, y: arg3 },
                        elevation: match arg4 {
                            0 => None,
                            1 => {
                                let e = arg5;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    });
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let LabeledPoint {
                        label: label3,
                        coords: coords3,
                        elevation: elevation3,
                    } = result1;
                    let vec4 = (label3.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr2.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                    let Point { x: x5, y: y5 } = coords3;
                    *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<f64>() = _rt::as_f64(
                        x5,
                    );
                    *ptr2
                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<f64>() = _rt::as_f64(y5);
                    match elevation3 {
                        Some(e) => {
                            *ptr2
                                .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            *ptr2
                                .add(24 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<f64>() = _rt::as_f64(e);
                        }
                        None => {
                            *ptr2
                                .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_echo_nested_record<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_list_u8_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::echo_list_u8(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_echo_list_u8<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_list_string_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base3 = arg0;
                    let len3 = arg1;
                    let mut result3 = _rt::Vec::with_capacity(len3);
                    for i in 0..len3 {
                        let base = base3
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e3 = {
                            let l0 = *base.add(0).cast::<*mut u8>();
                            let l1 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len2 = l1;
                            let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
                            _rt::string_lift(bytes2)
                        };
                        result3.push(e3);
                    }
                    _rt::cabi_dealloc(
                        base3,
                        len3 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result4 = T::echo_list_string(result3);
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec7 = result4;
                    let len7 = vec7.len();
                    let layout7 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec7.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result7 = if layout7.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout7).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout7);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec7.into_iter().enumerate() {
                        let base = result7
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec6 = (e.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    }
                    *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *ptr5.add(0).cast::<*mut u8>() = result7;
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_echo_list_string<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_list_record_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::echo_list_record(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_echo_list_record<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 16, 8);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_option_u32_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_option_u32(
                        match arg0 {
                            0 => None,
                            1 => {
                                let e = arg1 as u32;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Some(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            *ptr1.add(4).cast::<i32>() = _rt::as_i32(e);
                        }
                        None => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_option_string_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result1 = T::echo_option_string(
                        match arg0 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len0 = arg2;
                                    let bytes0 = _rt::Vec::from_raw_parts(
                                        arg1.cast(),
                                        len0,
                                        len0,
                                    );
                                    _rt::string_lift(bytes0)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Some(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                        None => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_echo_option_string<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_result_ok_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result2 = T::echo_result_ok(
                        match arg0 {
                            0 => {
                                let e = {
                                    let len0 = arg2;
                                    let bytes0 = _rt::Vec::from_raw_parts(
                                        arg1.cast(),
                                        len0,
                                        len0,
                                    );
                                    _rt::string_lift(bytes0)
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let len1 = arg2;
                                    let bytes1 = _rt::Vec::from_raw_parts(
                                        arg1.cast(),
                                        len1,
                                        len1,
                                    );
                                    _rt::string_lift(bytes1)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_echo_result_ok<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn echo_tuple2(v: (u32, _rt::String)) -> (u32, _rt::String);
                    fn echo_tuple3(v: (f32, f32, f32)) -> (f32, f32, f32);
                    fn echo_record(v: Point) -> Point;
                    fn echo_nested_record(v: LabeledPoint) -> LabeledPoint;
                    fn echo_list_u8(v: _rt::Vec<u8>) -> _rt::Vec<u8>;
                    fn echo_list_string(
                        v: _rt::Vec<_rt::String>,
                    ) -> _rt::Vec<_rt::String>;
                    fn echo_list_record(v: _rt::Vec<Point>) -> _rt::Vec<Point>;
                    fn echo_option_u32(v: Option<u32>) -> Option<u32>;
                    fn echo_option_string(v: Option<_rt::String>) -> Option<_rt::String>;
                    fn echo_result_ok(
                        v: Result<_rt::String, _rt::String>,
                    ) -> Result<_rt::String, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_jsco_test_echo_compound_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "jsco:test/echo-compound@0.1.0#echo-tuple2")] unsafe extern "C"
                        fn export_echo_tuple2(arg0 : i32, arg1 : * mut u8, arg2 : usize,)
                        -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_echo_tuple2_cabi::<$ty > (arg0, arg1, arg2) } } #[unsafe
                        (export_name =
                        "cabi_post_jsco:test/echo-compound@0.1.0#echo-tuple2")] unsafe
                        extern "C" fn _post_return_echo_tuple2(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_echo_tuple2::<$ty > (arg0) }
                        } #[unsafe (export_name =
                        "jsco:test/echo-compound@0.1.0#echo-tuple3")] unsafe extern "C"
                        fn export_echo_tuple3(arg0 : f32, arg1 : f32, arg2 : f32,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_echo_tuple3_cabi::<$ty > (arg0, arg1, arg2) } } #[unsafe
                        (export_name = "jsco:test/echo-compound@0.1.0#echo-record")]
                        unsafe extern "C" fn export_echo_record(arg0 : f64, arg1 : f64,)
                        -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_echo_record_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "jsco:test/echo-compound@0.1.0#echo-nested-record")] unsafe
                        extern "C" fn export_echo_nested_record(arg0 : * mut u8, arg1 :
                        usize, arg2 : f64, arg3 : f64, arg4 : i32, arg5 : f64,) -> * mut
                        u8 { unsafe { $($path_to_types)*::
                        _export_echo_nested_record_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_jsco:test/echo-compound@0.1.0#echo-nested-record")]
                        unsafe extern "C" fn _post_return_echo_nested_record(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_echo_nested_record::<$ty > (arg0) } } #[unsafe
                        (export_name = "jsco:test/echo-compound@0.1.0#echo-list-u8")]
                        unsafe extern "C" fn export_echo_list_u8(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_echo_list_u8_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_jsco:test/echo-compound@0.1.0#echo-list-u8")] unsafe
                        extern "C" fn _post_return_echo_list_u8(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_echo_list_u8::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "jsco:test/echo-compound@0.1.0#echo-list-string")] unsafe extern
                        "C" fn export_echo_list_string(arg0 : * mut u8, arg1 : usize,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_echo_list_string_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_jsco:test/echo-compound@0.1.0#echo-list-string")]
                        unsafe extern "C" fn _post_return_echo_list_string(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_echo_list_string::<$ty > (arg0) } } #[unsafe
                        (export_name = "jsco:test/echo-compound@0.1.0#echo-list-record")]
                        unsafe extern "C" fn export_echo_list_record(arg0 : * mut u8,
                        arg1 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_echo_list_record_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_jsco:test/echo-compound@0.1.0#echo-list-record")]
                        unsafe extern "C" fn _post_return_echo_list_record(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_echo_list_record::<$ty > (arg0) } } #[unsafe
                        (export_name = "jsco:test/echo-compound@0.1.0#echo-option-u32")]
                        unsafe extern "C" fn export_echo_option_u32(arg0 : i32, arg1 :
                        i32,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_echo_option_u32_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "jsco:test/echo-compound@0.1.0#echo-option-string")] unsafe
                        extern "C" fn export_echo_option_string(arg0 : i32, arg1 : * mut
                        u8, arg2 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_echo_option_string_cabi::<$ty > (arg0, arg1, arg2) } }
                        #[unsafe (export_name =
                        "cabi_post_jsco:test/echo-compound@0.1.0#echo-option-string")]
                        unsafe extern "C" fn _post_return_echo_option_string(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_echo_option_string::<$ty > (arg0) } } #[unsafe
                        (export_name = "jsco:test/echo-compound@0.1.0#echo-result-ok")]
                        unsafe extern "C" fn export_echo_result_ok(arg0 : i32, arg1 : *
                        mut u8, arg2 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_echo_result_ok_cabi::<$ty > (arg0,
                        arg1, arg2) } } #[unsafe (export_name =
                        "cabi_post_jsco:test/echo-compound@0.1.0#echo-result-ok")] unsafe
                        extern "C" fn _post_return_echo_result_ok(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_echo_result_ok::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_jsco_test_echo_compound_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 32 + 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 32
                        + 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// Algebraic: enums, variants, flags
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod echo_algebraic {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum Color {
                    Red,
                    Green,
                    Blue,
                    Yellow,
                }
                impl ::core::fmt::Debug for Color {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Color::Red => f.debug_tuple("Color::Red").finish(),
                            Color::Green => f.debug_tuple("Color::Green").finish(),
                            Color::Blue => f.debug_tuple("Color::Blue").finish(),
                            Color::Yellow => f.debug_tuple("Color::Yellow").finish(),
                        }
                    }
                }
                impl Color {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> Color {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => Color::Red,
                            1 => Color::Green,
                            2 => Color::Blue,
                            3 => Color::Yellow,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                wit_bindgen_rt::bitflags::bitflags! {
                    #[derive(PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy)]
                    pub struct Permissions : u8 { const READ = 1 << 0; const WRITE = 1 <<
                    1; const EXECUTE = 1 << 2; }
                }
                #[derive(Clone)]
                pub enum Shape {
                    Circle(f64),
                    Rectangle((f64, f64)),
                    NamedPolygon(_rt::String),
                    Dot,
                }
                impl ::core::fmt::Debug for Shape {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Shape::Circle(e) => {
                                f.debug_tuple("Shape::Circle").field(e).finish()
                            }
                            Shape::Rectangle(e) => {
                                f.debug_tuple("Shape::Rectangle").field(e).finish()
                            }
                            Shape::NamedPolygon(e) => {
                                f.debug_tuple("Shape::NamedPolygon").field(e).finish()
                            }
                            Shape::Dot => f.debug_tuple("Shape::Dot").finish(),
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_enum_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_enum(Color::_lift(arg0 as u8));
                    result0.clone() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_flags_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::echo_flags(
                        Permissions::empty()
                            | Permissions::from_bits_retain(((arg0 as u8) << 0) as _),
                    );
                    let flags1 = result0;
                    (flags1.bits() >> 0) as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_echo_variant_cabi<T: Guest>(
                    arg0: i32,
                    arg1: ::core::mem::MaybeUninit<u64>,
                    arg2: i64,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let v1 = match arg0 {
                        0 => {
                            let e1 = f64::from_bits(arg1.assume_init() as i64 as u64);
                            Shape::Circle(e1)
                        }
                        1 => {
                            let e1 = (
                                f64::from_bits(arg1.assume_init() as i64 as u64),
                                f64::from_bits(arg2 as u64),
                            );
                            Shape::Rectangle(e1)
                        }
                        2 => {
                            let e1 = {
                                let len0 = arg2 as usize;
                                let bytes0 = _rt::Vec::from_raw_parts(
                                    arg1.as_ptr().cast::<*mut u8>().read().cast(),
                                    len0,
                                    len0,
                                );
                                _rt::string_lift(bytes0)
                            };
                            Shape::NamedPolygon(e1)
                        }
                        n => {
                            debug_assert_eq!(n, 3, "invalid enum discriminant");
                            Shape::Dot
                        }
                    };
                    let result2 = T::echo_variant(v1);
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Shape::Circle(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr3.add(8).cast::<f64>() = _rt::as_f64(e);
                        }
                        Shape::Rectangle(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let (t4_0, t4_1) = e;
                            *ptr3.add(8).cast::<f64>() = _rt::as_f64(t4_0);
                            *ptr3.add(16).cast::<f64>() = _rt::as_f64(t4_1);
                        }
                        Shape::NamedPolygon(e) => {
                            *ptr3.add(0).cast::<u8>() = (2i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3.add(8).cast::<*mut u8>() = ptr5.cast_mut();
                        }
                        Shape::Dot => {
                            *ptr3.add(0).cast::<u8>() = (3i32) as u8;
                        }
                    }
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_echo_variant<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        1 => {}
                        2 => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {}
                    }
                }
                pub trait Guest {
                    fn echo_enum(v: Color) -> Color;
                    fn echo_flags(v: Permissions) -> Permissions;
                    fn echo_variant(v: Shape) -> Shape;
                }
                #[doc(hidden)]
                macro_rules! __export_jsco_test_echo_algebraic_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "jsco:test/echo-algebraic@0.1.0#echo-enum")] unsafe extern "C" fn
                        export_echo_enum(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_enum_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-algebraic@0.1.0#echo-flags")] unsafe extern "C"
                        fn export_echo_flags(arg0 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_echo_flags_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "jsco:test/echo-algebraic@0.1.0#echo-variant")] unsafe extern "C"
                        fn export_echo_variant(arg0 : i32, arg1 :
                        ::core::mem::MaybeUninit::< u64 >, arg2 : i64,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_echo_variant_cabi::<$ty >
                        (arg0, arg1, arg2) } } #[unsafe (export_name =
                        "cabi_post_jsco:test/echo-algebraic@0.1.0#echo-variant")] unsafe
                        extern "C" fn _post_return_echo_variant(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_echo_variant::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_jsco_test_echo_algebraic_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 24]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 24],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub unsafe fn char_lift(val: u32) -> char {
        if cfg!(debug_assertions) {
            core::char::from_u32(val).unwrap()
        } else {
            core::char::from_u32_unchecked(val)
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_echo_reactor_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::jsco::test::echo_primitives::__export_jsco_test_echo_primitives_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::jsco::test::echo_primitives);
        $($path_to_types_root)*::
        exports::jsco::test::echo_compound::__export_jsco_test_echo_compound_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::jsco::test::echo_compound);
        $($path_to_types_root)*::
        exports::jsco::test::echo_algebraic::__export_jsco_test_echo_algebraic_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::jsco::test::echo_algebraic);
    };
}
#[doc(inline)]
pub(crate) use __export_echo_reactor_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:jsco:echo-reactor:echo-reactor:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1256] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe5\x08\x01A\x02\x01\
A\x08\x01B\x04\x01@\x02\x05labels\x05values\x01\0\x04\0\x10report-primitive\x01\0\
\x01@\x03\x05labels\x01xu\x01yu\x01\0\x04\0\x0dreport-record\x01\x01\x03\0\x19js\
co:test/echo-sink@0.1.0\x05\0\x01B\x1a\x01@\x01\x01v\x7f\0\x7f\x04\0\x09echo-boo\
l\x01\0\x01@\x01\x01v}\0}\x04\0\x07echo-u8\x01\x01\x01@\x01\x01v{\0{\x04\0\x08ec\
ho-u16\x01\x02\x01@\x01\x01vy\0y\x04\0\x08echo-u32\x01\x03\x01@\x01\x01vw\0w\x04\
\0\x08echo-u64\x01\x04\x01@\x01\x01v~\0~\x04\0\x07echo-s8\x01\x05\x01@\x01\x01v|\
\0|\x04\0\x08echo-s16\x01\x06\x01@\x01\x01vz\0z\x04\0\x08echo-s32\x01\x07\x01@\x01\
\x01vx\0x\x04\0\x08echo-s64\x01\x08\x01@\x01\x01vv\0v\x04\0\x08echo-f32\x01\x09\x01\
@\x01\x01vu\0u\x04\0\x08echo-f64\x01\x0a\x01@\x01\x01vt\0t\x04\0\x09echo-char\x01\
\x0b\x01@\x01\x01vs\0s\x04\0\x0becho-string\x01\x0c\x04\0\x1fjsco:test/echo-prim\
itives@0.1.0\x05\x01\x01B!\x01r\x02\x01xu\x01yu\x04\0\x05point\x03\0\0\x01ku\x01\
r\x03\x05labels\x06coords\x01\x09elevation\x02\x04\0\x0dlabeled-point\x03\0\x03\x01\
o\x02ys\x01@\x01\x01v\x05\0\x05\x04\0\x0becho-tuple2\x01\x06\x01o\x03vvv\x01@\x01\
\x01v\x07\0\x07\x04\0\x0becho-tuple3\x01\x08\x01@\x01\x01v\x01\0\x01\x04\0\x0bec\
ho-record\x01\x09\x01@\x01\x01v\x04\0\x04\x04\0\x12echo-nested-record\x01\x0a\x01\
p}\x01@\x01\x01v\x0b\0\x0b\x04\0\x0cecho-list-u8\x01\x0c\x01ps\x01@\x01\x01v\x0d\
\0\x0d\x04\0\x10echo-list-string\x01\x0e\x01p\x01\x01@\x01\x01v\x0f\0\x0f\x04\0\x10\
echo-list-record\x01\x10\x01ky\x01@\x01\x01v\x11\0\x11\x04\0\x0fecho-option-u32\x01\
\x12\x01ks\x01@\x01\x01v\x13\0\x13\x04\0\x12echo-option-string\x01\x14\x01j\x01s\
\x01s\x01@\x01\x01v\x15\0\x15\x04\0\x0eecho-result-ok\x01\x16\x04\0\x1djsco:test\
/echo-compound@0.1.0\x05\x02\x01B\x0d\x01m\x04\x03red\x05green\x04blue\x06yellow\
\x04\0\x05color\x03\0\0\x01n\x03\x04read\x05write\x07execute\x04\0\x0bpermission\
s\x03\0\x02\x01o\x02uu\x01q\x04\x06circle\x01u\0\x09rectangle\x01\x04\0\x0dnamed\
-polygon\x01s\0\x03dot\0\0\x04\0\x05shape\x03\0\x05\x01@\x01\x01v\x01\0\x01\x04\0\
\x09echo-enum\x01\x07\x01@\x01\x01v\x03\0\x03\x04\0\x0aecho-flags\x01\x08\x01@\x01\
\x01v\x06\0\x06\x04\0\x0cecho-variant\x01\x09\x04\0\x1ejsco:test/echo-algebraic@\
0.1.0\x05\x03\x04\0\x1ejsco:echo-reactor/echo-reactor\x04\0\x0b\x12\x01\0\x0cech\
o-reactor\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.\
227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
