// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod hello {
    pub mod city {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod city {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct CityInfo {
                pub name: _rt::String,
                pub head_count: u32,
                pub budget: i64,
            }
            impl ::core::fmt::Debug for CityInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CityInfo")
                        .field("name", &self.name)
                        .field("head-count", &self.head_count)
                        .field("budget", &self.budget)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn send_message(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "hello:city/city")]
                    unsafe extern "C" {
                        #[link_name = "send-message"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod hello {
        pub mod city {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod greeter {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type CityInfo = super::super::super::super::hello::city::city::CityInfo;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: i64,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::run(super::super::super::super::hello::city::city::CityInfo {
                        name: _rt::string_lift(bytes0),
                        head_count: arg2 as u32,
                        budget: arg3,
                    });
                }
                pub trait Guest {
                    fn run(info: CityInfo) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_hello_city_greeter_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "hello:city/greeter#run")] unsafe extern "C" fn export_run(arg0 :
                        * mut u8, arg1 : usize, arg2 : i32, arg3 : i64,) { unsafe {
                        $($path_to_types)*:: _export_run_cabi::<$ty > (arg0, arg1, arg2,
                        arg3) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_hello_city_greeter_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_hello_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::hello::city::greeter::__export_hello_city_greeter_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::hello::city::greeter);
    };
}
#[doc(inline)]
pub(crate) use __export_hello_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:hello:city:hello:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 328] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xcc\x01\x01A\x02\x01\
A\x05\x01B\x04\x01r\x03\x04names\x0ahead-county\x06budgetx\x04\0\x09city-info\x03\
\0\0\x01@\x01\x07messages\x01\0\x04\0\x0csend-message\x01\x02\x03\0\x0fhello:cit\
y/city\x05\0\x02\x03\0\0\x09city-info\x01B\x04\x02\x03\x02\x01\x01\x04\0\x09city\
-info\x03\0\0\x01@\x01\x04info\x01\x01\0\x04\0\x03run\x01\x02\x04\0\x12hello:cit\
y/greeter\x05\x02\x04\0\x10hello:city/hello\x04\0\x0b\x0b\x01\0\x05hello\x03\0\0\
\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bind\
gen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
