// Copyright (c) 2023 Pavel Savara. Licensed under the MIT License.

import { ComponentImport } from '../parser/model/imports';
import { ModelTag } from '../parser/model/tags';
import { jsco_assert } from '../utils/assert';
import { lookupComponentInstance } from './component-instances';
import { stripImportPrefix } from './import-names';
import { JsImports } from './api-types';
import { validateImportType } from './type-validation';
import { Resolver, BinderRes } from './types';

/**
 * Resolve an import name from the JS imports object.
 * Handles both direct keys and namespaced names with '#' separators
 * (e.g., 'wasi:cli/stdin#get-stdin' → imports['wasi:cli/stdin']['get-stdin']).
 */
function resolveImportByName(imports: JsImports | undefined, name: string): unknown {
    if (!imports) return undefined;

    // Direct lookup
    if (name in imports) return imports[name];

    // For namespaced names like 'wasi:cli/stdin#get-stdin', split on '#'
    if (name.includes('#')) {
        const hashIdx = name.indexOf('#');
        const namespace = name.substring(0, hashIdx);
        const funcName = name.substring(hashIdx + 1);
        const ns = imports[namespace];
        if (ns && typeof ns === 'object') {
            return (ns as Record<string, unknown>)[funcName];
        }
    }

    return undefined;
}

export const resolveComponentImport: Resolver<ComponentImport> = (rctx, rargs) => {
    const componentImport = rargs.element;
    jsco_assert(componentImport && componentImport.tag == ModelTag.ComponentImport, () => `Wrong element type '${componentImport?.tag}'`);

    // Validate the import's type reference if type checking is enabled.
    // Only validate top-level imports (callerElement is undefined) — nested imports
    // inside component sections use section-local type indices.
    if (rctx.validateTypes && !rargs.callerElement) {
        validateImportType(rctx, componentImport);
    }

    switch (componentImport.ty.tag) {
        case ModelTag.ComponentTypeRefComponent: {
            const instanceIndex = rctx.importToInstanceIndex.get(componentImport.selfSortIndex!) ?? componentImport.selfSortIndex!;
            return {
                callerElement: rargs.callerElement,
                element: componentImport,
                binder: async (mctx, bargs) => {
                    const binderResult = lookupComponentInstance(mctx, instanceIndex);
                    const imprt = bargs.imports?.[componentImport.name.name];
                    // Imported functions are "exports" of this instance from the
                    // Component Model perspective — ComponentAliasInstanceExport reads from .exports
                    Object.assign(binderResult.result.exports, imprt);
                    return binderResult;
                }
            };
        }
        case ModelTag.ComponentTypeRefFunc: {
            // Function import: the component imports a function directly (not through an instance).
            // The JS imports object should have the function at the import name key.
            // Func imports contribute to componentFunctions[], so CanonicalFunctionLower
            // can reference them by func_index.
            return {
                callerElement: rargs.callerElement,
                element: componentImport,
                binder: async (mctx, bargs) => {
                    let importName = componentImport.name.name;
                    // Strip synthetic prefixes generated by wasm-tools compose.
                    // Composed components use prefixed names like "import-func-run"
                    // to disambiguate import kinds. The instantiation site strips
                    // these prefixes when building the args map, so the import
                    // lookup must strip them too to find the matching key.
                    importName = stripImportPrefix(importName);
                    const imprt = resolveImportByName(bargs.imports, importName);

                    const binderResult: BinderRes = {
                        result: imprt
                    };
                    return binderResult;
                }
            };
        }
        case ModelTag.ComponentTypeRefInstance: {
            // Instance import: the component imports an instance (interface).
            // The JS imports object should have the interface functions at the import name key.
            // Use the import→instance mapping because componentImports[] indices don't
            // necessarily equal componentInstances[] indices (interleaved type definitions,
            // non-instance imports, etc. shift the instance sort).
            const instanceIndex = rctx.importToInstanceIndex.get(componentImport.selfSortIndex!) ?? componentImport.selfSortIndex!;
            return {
                callerElement: rargs.callerElement,
                element: componentImport,
                binder: async (mctx, bargs) => {
                    const binderResult = lookupComponentInstance(mctx, instanceIndex);
                    const imprt = bargs.imports?.[componentImport.name.name];
                    Object.assign(binderResult.result.exports, imprt);
                    return binderResult;
                }
            };
        }
        case ModelTag.ComponentTypeRefType: {
            // Type imports: declarations that establish type information.
            // The actual wiring happens through other mechanisms (aliases, instantiation args).
            return {
                callerElement: rargs.callerElement,
                element: componentImport,
                binder: async (_mctx, _bargs) => {
                    const binderResult: BinderRes = {
                        result: undefined
                    };
                    return binderResult;
                }
            };
        }
        default:
            throw new Error(`${componentImport.ty.tag} not implemented`);

    }
};