// this is generated by JCO, slowly being replaced by JSCO

import { AbiPointer } from '../binding/types';

declare module js {
    declare type CityInfo = {
        name: string,
    }

    declare type Imports = {
        sendMessage: (message: string) => void;
    }

    declare type Exports = {
        run: (info: CityInfo) => void;
    }

    declare type NamedImports = {
        'hello:city/city': Imports
    }

    declare type NamedExports = {
        'hello:city/greeter': Exports
    }
}

declare module abi {
    export type module0Exports = {
        memory: WebAssembly.Memory
        cabi_realloc: Tcabi_realloc
        '__data_end': WebAssembly.Global
        '__heap_base': WebAssembly.Global
        'hello:city/greeter#run': (prt: AbiPointer, len: AbiPointer) => void,
    }

    export type module0Imports = {
        'hello:city/city': {
            'send-message': (prt: AbiPointer, len: AbiPointer) => void
        }
    }

    export type module2Imports = {
        '': {
            $imports: WebAssembly.Table
            '0': (prt: AbiPointer, len: AbiPointer) => void
        }
    }

    export type module1Exports = {
        '0': (prt: AbiPointer, len: AbiPointer) => void,
        $imports: WebAssembly.Table
    }
}
