// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod zoo {
    pub mod food {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod food {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum NutritionType {
                Carbohydrate,
                Protein,
                Vitamin,
            }
            impl ::core::fmt::Debug for NutritionType {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        NutritionType::Carbohydrate => {
                            f.debug_tuple("NutritionType::Carbohydrate").finish()
                        }
                        NutritionType::Protein => {
                            f.debug_tuple("NutritionType::Protein").finish()
                        }
                        NutritionType::Vitamin => {
                            f.debug_tuple("NutritionType::Vitamin").finish()
                        }
                    }
                }
            }
            impl NutritionType {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> NutritionType {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => NutritionType::Carbohydrate,
                        1 => NutritionType::Protein,
                        2 => NutritionType::Vitamin,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct NutritionInfo {
                pub percentage: f64,
                pub nutrition_type: NutritionType,
            }
            impl ::core::fmt::Debug for NutritionInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("NutritionInfo")
                        .field("percentage", &self.percentage)
                        .field("nutrition-type", &self.nutrition_type)
                        .finish()
                }
            }
            #[derive(Clone, Copy)]
            pub enum MaterialType {
                PlasticBag,
                MetalCan,
            }
            impl ::core::fmt::Debug for MaterialType {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        MaterialType::PlasticBag => {
                            f.debug_tuple("MaterialType::PlasticBag").finish()
                        }
                        MaterialType::MetalCan => {
                            f.debug_tuple("MaterialType::MetalCan").finish()
                        }
                    }
                }
            }
            wit_bindgen_rt::bitflags::bitflags! {
                #[derive(PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy)] pub
                struct SealingState : u8 { const OPENED = 1 << 0; const CLOSED = 1 << 1;
                const DAMAGED = 1 << 2; }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct PackageInfo {
                pub nutrition: NutritionInfo,
                pub material: MaterialType,
                pub sealing: SealingState,
            }
            impl ::core::fmt::Debug for PackageInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PackageInfo")
                        .field("nutrition", &self.nutrition)
                        .field("material", &self.material)
                        .field("sealing", &self.sealing)
                        .finish()
                }
            }
            /// flat record, do not nest:
            /// u32 is tested in hello
            #[derive(Clone)]
            pub struct FoodInfo {
                pub name: _rt::String,
                pub iso_code: char,
                pub weight: f32,
                pub healthy: bool,
                pub calories: u64,
                pub cost: u16,
                pub rating: i16,
                pub pieces: u8,
                /// tuple (Celcius, Fahrenheit)
                pub shelf_temperature: (i8, u8),
                pub cook_time_in_minutes: i32,
            }
            impl ::core::fmt::Debug for FoodInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("FoodInfo")
                        .field("name", &self.name)
                        .field("iso-code", &self.iso_code)
                        .field("weight", &self.weight)
                        .field("healthy", &self.healthy)
                        .field("calories", &self.calories)
                        .field("cost", &self.cost)
                        .field("rating", &self.rating)
                        .field("pieces", &self.pieces)
                        .field("shelf-temperature", &self.shelf_temperature)
                        .field("cook-time-in-minutes", &self.cook_time_in_minutes)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct MealPlan {
                pub foods: _rt::Vec<FoodInfo>,
                pub label: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for MealPlan {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("MealPlan")
                        .field("foods", &self.foods)
                        .field("label", &self.label)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn hide_food(food: &FoodInfo, message: &str) -> () {
                unsafe {
                    let FoodInfo {
                        name: name0,
                        iso_code: iso_code0,
                        weight: weight0,
                        healthy: healthy0,
                        calories: calories0,
                        cost: cost0,
                        rating: rating0,
                        pieces: pieces0,
                        shelf_temperature: shelf_temperature0,
                        cook_time_in_minutes: cook_time_in_minutes0,
                    } = food;
                    let vec1 = name0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let (t2_0, t2_1) = shelf_temperature0;
                    let vec3 = message;
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "zoo:food/food@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "hide-food"]
                        fn wit_import4(
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: f32,
                            _: i32,
                            _: i64,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import4(
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: f32,
                        _: i32,
                        _: i64,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import4(
                            ptr1.cast_mut(),
                            len1,
                            _rt::as_i32(iso_code0),
                            _rt::as_f32(weight0),
                            match healthy0 {
                                true => 1,
                                false => 0,
                            },
                            _rt::as_i64(calories0),
                            _rt::as_i32(cost0),
                            _rt::as_i32(rating0),
                            _rt::as_i32(pieces0),
                            _rt::as_i32(t2_0),
                            _rt::as_i32(t2_1),
                            _rt::as_i32(cook_time_in_minutes0),
                            ptr3.cast_mut(),
                            len3,
                        )
                    };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn consume_food(
                foodinfo: &FoodInfo,
                packageinfo: PackageInfo,
                message: &str,
            ) -> () {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 64 + 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 64
                            + 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    let FoodInfo {
                        name: name1,
                        iso_code: iso_code1,
                        weight: weight1,
                        healthy: healthy1,
                        calories: calories1,
                        cost: cost1,
                        rating: rating1,
                        pieces: pieces1,
                        shelf_temperature: shelf_temperature1,
                        cook_time_in_minutes: cook_time_in_minutes1,
                    } = foodinfo;
                    let vec2 = name1;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr0.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    *ptr0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                        iso_code1,
                    );
                    *ptr0
                        .add(4 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<f32>() = _rt::as_f32(weight1);
                    *ptr0
                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match healthy1 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    *ptr0
                        .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>() = _rt::as_i64(calories1);
                    *ptr0
                        .add(24 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u16>() = (_rt::as_i32(cost1)) as u16;
                    *ptr0
                        .add(26 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u16>() = (_rt::as_i32(rating1)) as u16;
                    *ptr0
                        .add(28 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (_rt::as_i32(pieces1)) as u8;
                    let (t3_0, t3_1) = shelf_temperature1;
                    *ptr0
                        .add(29 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (_rt::as_i32(t3_0)) as u8;
                    *ptr0
                        .add(30 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (_rt::as_i32(t3_1)) as u8;
                    *ptr0
                        .add(32 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>() = _rt::as_i32(cook_time_in_minutes1);
                    let PackageInfo {
                        nutrition: nutrition4,
                        material: material4,
                        sealing: sealing4,
                    } = packageinfo;
                    let NutritionInfo {
                        percentage: percentage5,
                        nutrition_type: nutrition_type5,
                    } = nutrition4;
                    *ptr0
                        .add(40 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<f64>() = _rt::as_f64(percentage5);
                    *ptr0
                        .add(48 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (nutrition_type5.clone() as i32) as u8;
                    match material4 {
                        MaterialType::PlasticBag => {
                            *ptr0
                                .add(56 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                        MaterialType::MetalCan => {
                            *ptr0
                                .add(56 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                        }
                    }
                    let flags6 = sealing4;
                    *ptr0
                        .add(57 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = ((flags6.bits() >> 0) as i32) as u8;
                    let vec7 = message;
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    *ptr0
                        .add(64 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len7;
                    *ptr0
                        .add(64 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr7.cast_mut();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "zoo:food/food@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "consume-food"]
                        fn wit_import8(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import8(_: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import8(ptr0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn open_package(
                sealingstate: SealingState,
                packageinfo: PackageInfo,
                message: &str,
            ) -> () {
                unsafe {
                    let flags0 = sealingstate;
                    let PackageInfo {
                        nutrition: nutrition1,
                        material: material1,
                        sealing: sealing1,
                    } = packageinfo;
                    let NutritionInfo {
                        percentage: percentage2,
                        nutrition_type: nutrition_type2,
                    } = nutrition1;
                    let result3 = match material1 {
                        MaterialType::PlasticBag => 0i32,
                        MaterialType::MetalCan => 1i32,
                    };
                    let flags4 = sealing1;
                    let vec5 = message;
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "zoo:food/food@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "open-package"]
                        fn wit_import6(
                            _: i32,
                            _: f64,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import6(
                        _: i32,
                        _: f64,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import6(
                            (flags0.bits() >> 0) as i32,
                            _rt::as_f64(percentage2),
                            nutrition_type2.clone() as i32,
                            result3,
                            (flags4.bits() >> 0) as i32,
                            ptr5.cast_mut(),
                            len5,
                        )
                    };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn trash_package(trashed: &[PackageInfo], message: &str) -> bool {
                unsafe {
                    let vec3 = trashed;
                    let len3 = vec3.len();
                    let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec3.len() * 24,
                        8,
                    );
                    let result3 = if layout3.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout3);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec3.into_iter().enumerate() {
                        let base = result3.add(i * 24);
                        {
                            let PackageInfo {
                                nutrition: nutrition0,
                                material: material0,
                                sealing: sealing0,
                            } = e;
                            let NutritionInfo {
                                percentage: percentage1,
                                nutrition_type: nutrition_type1,
                            } = nutrition0;
                            *base.add(0).cast::<f64>() = _rt::as_f64(percentage1);
                            *base.add(8).cast::<u8>() = (nutrition_type1.clone() as i32)
                                as u8;
                            match material0 {
                                MaterialType::PlasticBag => {
                                    *base.add(16).cast::<u8>() = (0i32) as u8;
                                }
                                MaterialType::MetalCan => {
                                    *base.add(16).cast::<u8>() = (1i32) as u8;
                                }
                            }
                            let flags2 = sealing0;
                            *base.add(17).cast::<u8>() = ((flags2.bits() >> 0) as i32)
                                as u8;
                        }
                    }
                    let vec4 = message;
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "zoo:food/food@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "trash-package"]
                        fn wit_import5(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        ) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import5(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import5(result3, len3, ptr4.cast_mut(), len4)
                    };
                    if layout3.size() != 0 {
                        _rt::alloc::dealloc(result3.cast(), layout3);
                    }
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn plan_meal(plan: &MealPlan) -> Result<_rt::String, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let MealPlan { foods: foods0, label: label0 } = plan;
                    let vec4 = foods0;
                    let len4 = vec4.len();
                    let layout4 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec4.len() * (40 + 2 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result4 = if layout4.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout4);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec4.into_iter().enumerate() {
                        let base = result4
                            .add(i * (40 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let FoodInfo {
                                name: name1,
                                iso_code: iso_code1,
                                weight: weight1,
                                healthy: healthy1,
                                calories: calories1,
                                cost: cost1,
                                rating: rating1,
                                pieces: pieces1,
                                shelf_temperature: shelf_temperature1,
                                cook_time_in_minutes: cook_time_in_minutes1,
                            } = e;
                            let vec2 = name1;
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(iso_code1);
                            *base
                                .add(4 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<f32>() = _rt::as_f32(weight1);
                            *base
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match healthy1 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            *base
                                .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(calories1);
                            *base
                                .add(24 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u16>() = (_rt::as_i32(cost1)) as u16;
                            *base
                                .add(26 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u16>() = (_rt::as_i32(rating1)) as u16;
                            *base
                                .add(28 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (_rt::as_i32(pieces1)) as u8;
                            let (t3_0, t3_1) = shelf_temperature1;
                            *base
                                .add(29 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (_rt::as_i32(t3_0)) as u8;
                            *base
                                .add(30 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (_rt::as_i32(t3_1)) as u8;
                            *base
                                .add(32 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(cook_time_in_minutes1);
                        }
                    }
                    let (result6_0, result6_1, result6_2) = match label0 {
                        Some(e) => {
                            let vec5 = e;
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            (1i32, ptr5.cast_mut(), len5)
                        }
                        None => (0i32, ::core::ptr::null_mut(), 0usize),
                    };
                    let ptr7 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "zoo:food/food@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "plan-meal"]
                        fn wit_import8(
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import8(
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import8(result4, len4, result6_0, result6_1, result6_2, ptr7)
                    };
                    let l9 = i32::from(*ptr7.add(0).cast::<u8>());
                    let result16 = match l9 {
                        0 => {
                            let e = {
                                let l10 = *ptr7
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l11 = *ptr7
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len12 = l11;
                                let bytes12 = _rt::Vec::from_raw_parts(
                                    l10.cast(),
                                    len12,
                                    len12,
                                );
                                _rt::string_lift(bytes12)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l13 = *ptr7
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l14 = *ptr7
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len15 = l14;
                                let bytes15 = _rt::Vec::from_raw_parts(
                                    l13.cast(),
                                    len15,
                                    len15,
                                );
                                _rt::string_lift(bytes15)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    if layout4.size() != 0 {
                        _rt::alloc::dealloc(result4.cast(), layout4);
                    }
                    result16
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod eater {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type FoodInfo = super::super::super::zoo::food::food::FoodInfo;
            pub type PackageInfo = super::super::super::zoo::food::food::PackageInfo;
            pub type MealPlan = super::super::super::zoo::food::food::MealPlan;
            #[allow(unused_unsafe, clippy::all)]
            pub fn feed(foodinfo: &FoodInfo, packageinfo: PackageInfo) -> () {
                unsafe {
                    let super::super::super::zoo::food::food::FoodInfo {
                        name: name0,
                        iso_code: iso_code0,
                        weight: weight0,
                        healthy: healthy0,
                        calories: calories0,
                        cost: cost0,
                        rating: rating0,
                        pieces: pieces0,
                        shelf_temperature: shelf_temperature0,
                        cook_time_in_minutes: cook_time_in_minutes0,
                    } = foodinfo;
                    let vec1 = name0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let (t2_0, t2_1) = shelf_temperature0;
                    let super::super::super::zoo::food::food::PackageInfo {
                        nutrition: nutrition3,
                        material: material3,
                        sealing: sealing3,
                    } = packageinfo;
                    let super::super::super::zoo::food::food::NutritionInfo {
                        percentage: percentage4,
                        nutrition_type: nutrition_type4,
                    } = nutrition3;
                    use super::super::super::zoo::food::food::MaterialType as V5;
                    let result6 = match material3 {
                        V5::PlasticBag => 0i32,
                        V5::MetalCan => 1i32,
                    };
                    let flags7 = sealing3;
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "zoo:food/eater@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "feed"]
                        fn wit_import8(
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: f32,
                            _: i32,
                            _: i64,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: f64,
                            _: i32,
                            _: i32,
                            _: i32,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import8(
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: f32,
                        _: i32,
                        _: i64,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: f64,
                        _: i32,
                        _: i32,
                        _: i32,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import8(
                            ptr1.cast_mut(),
                            len1,
                            _rt::as_i32(iso_code0),
                            _rt::as_f32(weight0),
                            match healthy0 {
                                true => 1,
                                false => 0,
                            },
                            _rt::as_i64(calories0),
                            _rt::as_i32(cost0),
                            _rt::as_i32(rating0),
                            _rt::as_i32(pieces0),
                            _rt::as_i32(t2_0),
                            _rt::as_i32(t2_1),
                            _rt::as_i32(cook_time_in_minutes0),
                            _rt::as_f64(percentage4),
                            nutrition_type4.clone() as i32,
                            result6,
                            (flags7.bits() >> 0) as i32,
                        )
                    };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn schedule(plan: &MealPlan) -> Result<_rt::String, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let super::super::super::zoo::food::food::MealPlan {
                        foods: foods0,
                        label: label0,
                    } = plan;
                    let vec4 = foods0;
                    let len4 = vec4.len();
                    let layout4 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec4.len() * (40 + 2 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result4 = if layout4.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout4);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec4.into_iter().enumerate() {
                        let base = result4
                            .add(i * (40 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let super::super::super::zoo::food::food::FoodInfo {
                                name: name1,
                                iso_code: iso_code1,
                                weight: weight1,
                                healthy: healthy1,
                                calories: calories1,
                                cost: cost1,
                                rating: rating1,
                                pieces: pieces1,
                                shelf_temperature: shelf_temperature1,
                                cook_time_in_minutes: cook_time_in_minutes1,
                            } = e;
                            let vec2 = name1;
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(iso_code1);
                            *base
                                .add(4 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<f32>() = _rt::as_f32(weight1);
                            *base
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match healthy1 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            *base
                                .add(16 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(calories1);
                            *base
                                .add(24 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u16>() = (_rt::as_i32(cost1)) as u16;
                            *base
                                .add(26 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u16>() = (_rt::as_i32(rating1)) as u16;
                            *base
                                .add(28 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (_rt::as_i32(pieces1)) as u8;
                            let (t3_0, t3_1) = shelf_temperature1;
                            *base
                                .add(29 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (_rt::as_i32(t3_0)) as u8;
                            *base
                                .add(30 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (_rt::as_i32(t3_1)) as u8;
                            *base
                                .add(32 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(cook_time_in_minutes1);
                        }
                    }
                    let (result6_0, result6_1, result6_2) = match label0 {
                        Some(e) => {
                            let vec5 = e;
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            (1i32, ptr5.cast_mut(), len5)
                        }
                        None => (0i32, ::core::ptr::null_mut(), 0usize),
                    };
                    let ptr7 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "zoo:food/eater@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "schedule"]
                        fn wit_import8(
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import8(
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import8(result4, len4, result6_0, result6_1, result6_2, ptr7)
                    };
                    let l9 = i32::from(*ptr7.add(0).cast::<u8>());
                    let result16 = match l9 {
                        0 => {
                            let e = {
                                let l10 = *ptr7
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l11 = *ptr7
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len12 = l11;
                                let bytes12 = _rt::Vec::from_raw_parts(
                                    l10.cast(),
                                    len12,
                                    len12,
                                );
                                _rt::string_lift(bytes12)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l13 = *ptr7
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l14 = *ptr7
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len15 = l14;
                                let bytes15 = _rt::Vec::from_raw_parts(
                                    l13.cast(),
                                    len15,
                                    len15,
                                );
                                _rt::string_lift(bytes15)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    if layout4.size() != 0 {
                        _rt::alloc::dealloc(result4.cast(), layout4);
                    }
                    result16
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod city {
        pub mod runner {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod runner {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::run();
                }
                pub trait Guest {
                    fn run() -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_city_runner_runner_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "city:runner/runner@0.1.0#run")] unsafe extern "C" fn
                        export_run() { unsafe { $($path_to_types)*::
                        _export_run_cabi::<$ty > () } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_city_runner_runner_0_1_0_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_city_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::city::runner::runner::__export_city_runner_runner_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::city::runner::runner);
    };
}
#[doc(inline)]
pub(crate) use __export_city_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:city:runner@0.1.0:city:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1065] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xae\x07\x01A\x02\x01\
A\x09\x01B\x1d\x01m\x03\x0ccarbohydrate\x07protein\x07vitamin\x04\0\x0enutrition\
-type\x03\0\0\x01r\x02\x0apercentageu\x0enutrition-type\x01\x04\0\x0enutrition-i\
nfo\x03\0\x02\x01q\x02\x0bplastic-bag\0\0\x09metal-can\0\0\x04\0\x0dmaterial-typ\
e\x03\0\x04\x01n\x03\x06opened\x06closed\x07damaged\x04\0\x0dsealing-state\x03\0\
\x06\x01r\x03\x09nutrition\x03\x08material\x05\x07sealing\x07\x04\0\x0cpackage-i\
nfo\x03\0\x08\x01o\x02~}\x01r\x0a\x04names\x08iso-codet\x06weightv\x07healthy\x7f\
\x08caloriesw\x04cost{\x06rating|\x06pieces}\x11shelf-temperature\x0a\x14cook-ti\
me-in-minutesz\x04\0\x09food-info\x03\0\x0b\x01p\x0c\x01ks\x01r\x02\x05foods\x0d\
\x05label\x0e\x04\0\x09meal-plan\x03\0\x0f\x01@\x02\x04food\x0c\x07messages\x01\0\
\x04\0\x09hide-food\x01\x11\x01@\x03\x08foodinfo\x0c\x0bpackageinfo\x09\x07messa\
ges\x01\0\x04\0\x0cconsume-food\x01\x12\x01@\x03\x0csealingstate\x07\x0bpackagei\
nfo\x09\x07messages\x01\0\x04\0\x0copen-package\x01\x13\x01p\x09\x01@\x02\x07tra\
shed\x14\x07messages\0\x7f\x04\0\x0dtrash-package\x01\x15\x01j\x01s\x01s\x01@\x01\
\x04plan\x10\0\x16\x04\0\x09plan-meal\x01\x17\x03\0\x13zoo:food/food@0.1.0\x05\0\
\x02\x03\0\0\x09food-info\x02\x03\0\0\x0cpackage-info\x02\x03\0\0\x09meal-plan\x01\
B\x0b\x02\x03\x02\x01\x01\x04\0\x09food-info\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0c\
package-info\x03\0\x02\x02\x03\x02\x01\x03\x04\0\x09meal-plan\x03\0\x04\x01@\x02\
\x08foodinfo\x01\x0bpackageinfo\x03\x01\0\x04\0\x04feed\x01\x06\x01j\x01s\x01s\x01\
@\x01\x04plan\x05\0\x07\x04\0\x08schedule\x01\x08\x03\0\x14zoo:food/eater@0.1.0\x05\
\x04\x01B\x02\x01@\0\x01\0\x04\0\x03run\x01\0\x04\0\x18city:runner/runner@0.1.0\x05\
\x05\x04\0\x16city:runner/city@0.1.0\x04\0\x0b\x0a\x01\0\x04city\x03\0\0\0G\x09p\
roducers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\
\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
