// world wasi:cli/command@0.2.11
export type * as WasiCliEnvironment0211 from './interfaces/wasi-cli-environment.js'; // import wasi:cli/environment@0.2.11
export type * as WasiCliExit0211 from './interfaces/wasi-cli-exit.js'; // import wasi:cli/exit@0.2.11
export type * as WasiCliStderr0211 from './interfaces/wasi-cli-stderr.js'; // import wasi:cli/stderr@0.2.11
export type * as WasiCliStdin0211 from './interfaces/wasi-cli-stdin.js'; // import wasi:cli/stdin@0.2.11
export type * as WasiCliStdout0211 from './interfaces/wasi-cli-stdout.js'; // import wasi:cli/stdout@0.2.11
export type * as WasiCliTerminalInput0211 from './interfaces/wasi-cli-terminal-input.js'; // import wasi:cli/terminal-input@0.2.11
export type * as WasiCliTerminalOutput0211 from './interfaces/wasi-cli-terminal-output.js'; // import wasi:cli/terminal-output@0.2.11
export type * as WasiCliTerminalStderr0211 from './interfaces/wasi-cli-terminal-stderr.js'; // import wasi:cli/terminal-stderr@0.2.11
export type * as WasiCliTerminalStdin0211 from './interfaces/wasi-cli-terminal-stdin.js'; // import wasi:cli/terminal-stdin@0.2.11
export type * as WasiCliTerminalStdout0211 from './interfaces/wasi-cli-terminal-stdout.js'; // import wasi:cli/terminal-stdout@0.2.11
export type * as WasiClocksMonotonicClock0211 from './interfaces/wasi-clocks-monotonic-clock.js'; // import wasi:clocks/monotonic-clock@0.2.11
export type * as WasiClocksTimezone0211 from './interfaces/wasi-clocks-timezone.js'; // import wasi:clocks/timezone@0.2.11
export type * as WasiClocksWallClock0211 from './interfaces/wasi-clocks-wall-clock.js'; // import wasi:clocks/wall-clock@0.2.11
export type * as WasiFilesystemPreopens0211 from './interfaces/wasi-filesystem-preopens.js'; // import wasi:filesystem/preopens@0.2.11
export type * as WasiFilesystemTypes0211 from './interfaces/wasi-filesystem-types.js'; // import wasi:filesystem/types@0.2.11
export type * as WasiIoError0211 from './interfaces/wasi-io-error.js'; // import wasi:io/error@0.2.11
export type * as WasiIoPoll0211 from './interfaces/wasi-io-poll.js'; // import wasi:io/poll@0.2.11
export type * as WasiIoStreams0211 from './interfaces/wasi-io-streams.js'; // import wasi:io/streams@0.2.11
export type * as WasiRandomInsecureSeed0211 from './interfaces/wasi-random-insecure-seed.js'; // import wasi:random/insecure-seed@0.2.11
export type * as WasiRandomInsecure0211 from './interfaces/wasi-random-insecure.js'; // import wasi:random/insecure@0.2.11
export type * as WasiRandomRandom0211 from './interfaces/wasi-random-random.js'; // import wasi:random/random@0.2.11
export type * as WasiSocketsInstanceNetwork0211 from './interfaces/wasi-sockets-instance-network.js'; // import wasi:sockets/instance-network@0.2.11
export type * as WasiSocketsIpNameLookup0211 from './interfaces/wasi-sockets-ip-name-lookup.js'; // import wasi:sockets/ip-name-lookup@0.2.11
export type * as WasiSocketsNetwork0211 from './interfaces/wasi-sockets-network.js'; // import wasi:sockets/network@0.2.11
export type * as WasiSocketsTcpCreateSocket0211 from './interfaces/wasi-sockets-tcp-create-socket.js'; // import wasi:sockets/tcp-create-socket@0.2.11
export type * as WasiSocketsTcp0211 from './interfaces/wasi-sockets-tcp.js'; // import wasi:sockets/tcp@0.2.11
export type * as WasiSocketsUdpCreateSocket0211 from './interfaces/wasi-sockets-udp-create-socket.js'; // import wasi:sockets/udp-create-socket@0.2.11
export type * as WasiSocketsUdp0211 from './interfaces/wasi-sockets-udp.js'; // import wasi:sockets/udp@0.2.11
export * as run from './interfaces/wasi-cli-run.js'; // export wasi:cli/run@0.2.11
