package zoo:city

interface city {
    record city-info {
        name: string,
        head-count: u32,
        budget: s64,
    }

    send-message: func(message: string)
}

interface greeter {
    use city.{city-info}
    run: func(info: city-info)
}

world zoo {
    import city
    export greeter
}
