package jsco:consumer-p2@0.1.0;

world consumer-p2 {
    import wasi:cli/environment@0.2.11;
    import wasi:cli/exit@0.2.11;
    import wasi:cli/stdin@0.2.11;
    import wasi:cli/stdout@0.2.11;
    import wasi:cli/stderr@0.2.11;
    import wasi:io/error@0.2.11;
    import wasi:io/poll@0.2.11;
    import wasi:io/streams@0.2.11;
    import wasi:random/random@0.2.11;
    import wasi:clocks/monotonic-clock@0.2.11;
    import wasi:clocks/wall-clock@0.2.11;
    import jsco:test/logger@0.1.0;
    import jsco:test/counter@0.1.0;
    import jsco:test/echo-primitives@0.1.0;
    import jsco:test/echo-compound@0.1.0;
    import jsco:test/echo-algebraic@0.1.0;
    import jsco:test/echo-complex@0.1.0;
    import jsco:test/echo-resources@0.1.0;
    export wasi:cli/run@0.2.11;
}
