name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ContinuousIntegrationBuild: true
      Configuration: Release

    steps:
    - uses: actions/checkout@v3
    - name: Install npm dependencies
      run: npm install -ci

    - name: Rollup project
      working-directory: ./hello
      run: npm run build:npm

    - name: Run hello sample as sanity check
      working-directory: ./hello
      run: npm run test:usage

    - name: Rollup artifact
      uses: actions/upload-artifact@v3
      with:
        name: jsco.${{github.sha}}
        path: |
          dist/*.*
          dist/LICENSE
