name: jest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --experimental-vm-modules

    steps:
    - uses: actions/checkout@v3
    - name: Install npm dependencies
      run: npm install -ci

    - name: Run Jest unit tests
      working-directory: ./hello
      run: npm run test:ci
