name: rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustc, rustfmt, rust-std, cargo

    - uses: Swatinem/rust-cache@v2.6.2
      with:
        cache-all-crates: true
        cache-targets: true
        workspaces: "hello"

    - name: Install JCO
      run: npm install

    - name: Build rust demo
      run: npm run build:hello

    - name: Export demo as .wat
      run: npm run build:hello-wat

    - name: Export demo as .wat JCO javaScript
      run: npm run build:hello-js

    - name: Sanity test that JCO can run hello component
      run: npm run test:jco

    - name: WASM component artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello.${{github.sha}}
        path: hello/target/wasm32-unknown-unknown/release/hello.wa*

    - name: JCO component artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-jco.${{github.sha}}
        path: hello/target/js-jco/**/*.*
