name: rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: npm run setup:rust
      working-directory: ./hello

    - uses: Swatinem/rust-cache@v2.6.2
      with:
        cache-all-crates: true
        cache-targets: true
        workspaces: "hello"

    - name: Install JCO
      run: npm install @bytecodealliance/jco -g

    - name: Build rust demo
      working-directory: ./hello
      run: npm run build:hello

    - name: Export demo as .wat
      working-directory: ./hello
      run: npm run build:hello

    - name: Export demo as .wat JCO javaScript
      working-directory: ./hello
      run: npm run build:hello-js

    - name: Sanity test that JCO can run hello component
      working-directory: ./hello
      run: npm run test:jco

    - name: WASM component artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello.${{github.sha}}.wasm
        path: hello/target/wasm32-unknown-unknown/release/hello.wa*

    - name: JCO component artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello.${{github.sha}}.wasm
        path: hello/target/js-jco/**/*.*
