name: rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths: [ "integration-tests/**", "wit/**", ".github/workflows/rust.yml" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install latest stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown,wasm32-wasip1

    - uses: Swatinem/rust-cache@v2.9.1
      with:
        cache-all-crates: true
        cache-targets: true
        workspaces: |
          integration-tests
        cache-on-failure: true

    - name: Install cargo-component
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-component
        locked: true

    - name: Install wasm-tools
      uses: baptiste0928/cargo-install@v3
      with:
        crate: wasm-tools
        locked: true

    - name: Install wac-cli
      uses: baptiste0928/cargo-install@v3
      with:
        crate: wac-cli
        locked: true

    - name: Install JCO
      run: npm install

    - name: Build integration test components
      run: npm run build:integration

    - name: Build wac compositions
      run: npm run build:compositions

    - name: Integration test component artifacts
      uses: actions/upload-artifact@v6
      with:
        name: integration.${{github.sha}}
        path: |
          integration-tests/target/wasm32-wasip1/release/*.wasm
          integration-tests/target/wasm32-unknown-unknown/release/implementer.wasm
          integration-tests/compositions/*.wasm
